sudo: required
dist: trusty
language: python
python:
  - "2.7"

before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

script:
  - bash -xve ./test/travis_ros_install.bash
