sudo: required
dist: trusty
language: python
python:
  - "2.7"

before_script:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
script:
  - bash -xve ./test/travis_ros_install.bash
  - source ~/catkin_ws/devel/setup.bash
  - bash -xve ./test/travis_package_make.bash
